#!/usr/bin/env bash

readonly domain=seabears.net
export SB_BASEURL="http://$domain"
export SB_BLOG="$(pwd)/../softwarebears-blog/"
export SB_DESCRIPTION="Writing about technology from an engineer's point of view."

deploy() {
	lein uberjar
	java -jar target/uberjar/softwarebears-*-standalone.jar $1
	cp -r resources/public/* $1
	cp -r $SB_BLOG/img/ $1
	echo -n $domain > "$1/CNAME"
}

deploy docs/

