#!/usr/bin/env bash

export SB_BASEURL="http://softwarebears.com"
export SB_BLOG="$(pwd)/../softwarebears-blog/"

deploy() {
	lein uberjar
	java -jar target/uberjar/softwarebears-*-standalone.jar $1
	cp -r resources/public/* $1
}

deploy docs/

